//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBM00100FrontResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CBM00100FrontResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CBM00100FrontResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CBM00100FrontResources.CBM00100FrontResources_msgrsc", typeof(CBM00100FrontResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Cancel Soft Close.
        /// </summary>
        internal static string _AllowCancelSoftClose {
            get {
                return ResourceManager.GetString("_AllowCancelSoftClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank-in Mode.
        /// </summary>
        internal static string _BankInMode {
            get {
                return ResourceManager.GetString("_BankInMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string _BtnCancel {
            get {
                return ResourceManager.GetString("_BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string _BtnCreate {
            get {
                return ResourceManager.GetString("_BtnCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By.
        /// </summary>
        internal static string _By {
            get {
                return ResourceManager.GetString("_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CB Link Date*.
        /// </summary>
        internal static string _CBLinkDate {
            get {
                return ResourceManager.GetString("_CBLinkDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque.
        /// </summary>
        internal static string _Cheque {
            get {
                return ResourceManager.GetString("_Cheque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing in Progress.
        /// </summary>
        internal static string _ClosingInProgress {
            get {
                return ResourceManager.GetString("_ClosingInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contra Account*.
        /// </summary>
        internal static string _ContraAccount {
            get {
                return ResourceManager.GetString("_ContraAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create By.
        /// </summary>
        internal static string _CreatedBy {
            get {
                return ResourceManager.GetString("_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Period.
        /// </summary>
        internal static string _CurrentPeriod {
            get {
                return ResourceManager.GetString("_CurrentPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Rate Type.
        /// </summary>
        internal static string _CurrRateType {
            get {
                return ResourceManager.GetString("_CurrRateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Numbering by Cash/Bank Code.
        /// </summary>
        internal static string _DocNumByCashOrBank {
            get {
                return ResourceManager.GetString("_DocNumByCashOrBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Input Cheque Due Date.
        /// </summary>
        internal static string _EnableInputChequeDueDate {
            get {
                return ResourceManager.GetString("_EnableInputChequeDueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forex Gain Account*.
        /// </summary>
        internal static string _ForexGainAccount {
            get {
                return ResourceManager.GetString("_ForexGainAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forex Loss Account*.
        /// </summary>
        internal static string _ForexLossAccount {
            get {
                return ResourceManager.GetString("_ForexLossAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Setup.
        /// </summary>
        internal static string _JournalSetup {
            get {
                return ResourceManager.GetString("_JournalSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CB System Parameter for this property has not been created!.
        /// </summary>
        internal static string _L01 {
            get {
                return ResourceManager.GetString("_L01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard Changes?.
        /// </summary>
        internal static string _N01 {
            get {
                return ResourceManager.GetString("_N01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CB System Parameter Created Successfully!.
        /// </summary>
        internal static string _N02 {
            get {
                return ResourceManager.GetString("_N02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        internal static string _Period {
            get {
                return ResourceManager.GetString("_Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Through Batch Clearing Cheque.
        /// </summary>
        internal static string _RadioBBankInMode {
            get {
                return ResourceManager.GetString("_RadioBBankInMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearing Cheque Directly.
        /// </summary>
        internal static string _RadioDBankInMode {
            get {
                return ResourceManager.GetString("_RadioDBankInMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soft Close Period.
        /// </summary>
        internal static string _SoftClosePeriod {
            get {
                return ResourceManager.GetString("_SoftClosePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated By.
        /// </summary>
        internal static string _UpdatedBy {
            get {
                return ResourceManager.GetString("_UpdatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Rate Type is required!.
        /// </summary>
        internal static string V01 {
            get {
                return ResourceManager.GetString("V01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CB Link Date is required!.
        /// </summary>
        internal static string V02 {
            get {
                return ResourceManager.GetString("V02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contra Account is required!.
        /// </summary>
        internal static string V03 {
            get {
                return ResourceManager.GetString("V03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forex Gain Account is required!.
        /// </summary>
        internal static string V04 {
            get {
                return ResourceManager.GetString("V04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forex Loss Account is required!.
        /// </summary>
        internal static string V05 {
            get {
                return ResourceManager.GetString("V05", resourceCulture);
            }
        }
    }
}
