//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSM09100FrontResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GSM09100FrontResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GSM09100FrontResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GSM09100FrontResources.GSM09100FrontResources_msgrsc", typeof(GSM09100FrontResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Code is required!.
        /// </summary>
        internal static string _901 {
            get {
                return ResourceManager.GetString("901", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name is required!.
        /// </summary>
        internal static string _902 {
            get {
                return ResourceManager.GetString("902", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string _Active {
            get {
                return ResourceManager.GetString("_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias ID.
        /// </summary>
        internal static string _AliasId {
            get {
                return ResourceManager.GetString("_AliasId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias Name.
        /// </summary>
        internal static string _AliasName {
            get {
                return ResourceManager.GetString("_AliasName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string _CancelBtn {
            get {
                return ResourceManager.GetString("_CancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Code*.
        /// </summary>
        internal static string _CatCode {
            get {
                return ResourceManager.GetString("_CatCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name*.
        /// </summary>
        internal static string _CatName {
            get {
                return ResourceManager.GetString("_CatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        internal static string _CreateBy {
            get {
                return ResourceManager.GetString("_CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        internal static string _CreateDate {
            get {
                return ResourceManager.GetString("_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Product Category.
        /// </summary>
        internal static string _FromProductCat {
            get {
                return ResourceManager.GetString("_FromProductCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string _Level {
            get {
                return ResourceManager.GetString("_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        internal static string _MoveBtn {
            get {
                return ResourceManager.GetString("_MoveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string _Notes {
            get {
                return ResourceManager.GetString("_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven’t saved your changes. Are you sure want to cancel?.
        /// </summary>
        internal static string _NotifCancelSave {
            get {
                return ResourceManager.GetString("_NotifCancelSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Deleted Successfully!.
        /// </summary>
        internal static string _NotifCategoryDelete {
            get {
                return ResourceManager.GetString("_NotifCategoryDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Product Category cannot be the same with From Product Category!.
        /// </summary>
        internal static string _NotifDuplicateCategory {
            get {
                return ResourceManager.GetString("_NotifDuplicateCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Product Category Is Required.
        /// </summary>
        internal static string _NotifProductCatReq {
            get {
                return ResourceManager.GetString("_NotifProductCatReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Product Is Success.
        /// </summary>
        internal static string _NotifProductMoveSuccess {
            get {
                return ResourceManager.GetString("_NotifProductMoveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Category.
        /// </summary>
        internal static string _ParentCategory {
            get {
                return ResourceManager.GetString("_ParentCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        internal static string _ProcessBtn {
            get {
                return ResourceManager.GetString("_ProcessBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product ID.
        /// </summary>
        internal static string _ProductId {
            get {
                return ResourceManager.GetString("_ProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        internal static string _ProductName {
            get {
                return ResourceManager.GetString("_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string _Property {
            get {
                return ResourceManager.GetString("_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string _Status {
            get {
                return ResourceManager.GetString("_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Categories.
        /// </summary>
        internal static string _TabProductCategory {
            get {
                return ResourceManager.GetString("_TabProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product List.
        /// </summary>
        internal static string _TabProductList {
            get {
                return ResourceManager.GetString("_TabProductList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Product Category.
        /// </summary>
        internal static string _ToProductCat {
            get {
                return ResourceManager.GetString("_ToProductCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated By.
        /// </summary>
        internal static string _UpdateBy {
            get {
                return ResourceManager.GetString("_UpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Date.
        /// </summary>
        internal static string _UpdateDate {
            get {
                return ResourceManager.GetString("_UpdateDate", resourceCulture);
            }
        }
    }
}
