//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMM06500FrontResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LMM06500FrontResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LMM06500FrontResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LMM06500FrontResources.LMM06500FrontResources_msgrsc", typeof(LMM06500FrontResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff ID is required.
        /// </summary>
        internal static string _6514 {
            get {
                return ResourceManager.GetString("6514", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Name is required.
        /// </summary>
        internal static string _6515 {
            get {
                return ResourceManager.GetString("6515", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Email is required.
        /// </summary>
        internal static string _6516 {
            get {
                return ResourceManager.GetString("6516", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Mobile Phone 1 is required.
        /// </summary>
        internal static string _6517 {
            get {
                return ResourceManager.GetString("6517", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Gender is required.
        /// </summary>
        internal static string _6518 {
            get {
                return ResourceManager.GetString("6518", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff ID Maximum 20 Character.
        /// </summary>
        internal static string _6519 {
            get {
                return ResourceManager.GetString("6519", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Name Maximum 100 Character.
        /// </summary>
        internal static string _6520 {
            get {
                return ResourceManager.GetString("6520", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Phone 1 Maximum 30 Character.
        /// </summary>
        internal static string _6521 {
            get {
                return ResourceManager.GetString("6521", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Phone 2 Maximum 30 Character.
        /// </summary>
        internal static string _6522 {
            get {
                return ResourceManager.GetString("6522", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Maximum 100 Character.
        /// </summary>
        internal static string _6523 {
            get {
                return ResourceManager.GetString("6523", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select City!.
        /// </summary>
        internal static string _6524 {
            get {
                return ResourceManager.GetString("6524", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Department!.
        /// </summary>
        internal static string _6525 {
            get {
                return ResourceManager.GetString("6525", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Position!.
        /// </summary>
        internal static string _6526 {
            get {
                return ResourceManager.GetString("6526", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Supervisor!.
        /// </summary>
        internal static string _6527 {
            get {
                return ResourceManager.GetString("6527", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string _Active {
            get {
                return ResourceManager.GetString("_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string _Address {
            get {
                return ResourceManager.GetString("_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string _CancelBtn {
            get {
                return ResourceManager.GetString("_CancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string _City {
            get {
                return ResourceManager.GetString("_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string _Country {
            get {
                return ResourceManager.GetString("_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        internal static string _CreateBy {
            get {
                return ResourceManager.GetString("_CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        internal static string _CreateDate {
            get {
                return ResourceManager.GetString("_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departement.
        /// </summary>
        internal static string _Dept {
            get {
                return ResourceManager.GetString("_Dept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string _EmailAddress {
            get {
                return ResourceManager.GetString("_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string _Gender {
            get {
                return ResourceManager.GetString("_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive Date.
        /// </summary>
        internal static string _InactiveDate {
            get {
                return ResourceManager.GetString("_InactiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive Note.
        /// </summary>
        internal static string _InactiveNote {
            get {
                return ResourceManager.GetString("_InactiveNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        internal static string _Invalid {
            get {
                return ResourceManager.GetString("_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Date.
        /// </summary>
        internal static string _JoinDate {
            get {
                return ResourceManager.GetString("_JoinDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No 1.
        /// </summary>
        internal static string _MobileNo1 {
            get {
                return ResourceManager.GetString("_MobileNo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No(1).
        /// </summary>
        internal static string _MobilePhone1 {
            get {
                return ResourceManager.GetString("_MobilePhone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No(2).
        /// </summary>
        internal static string _MobilePhone2 {
            get {
                return ResourceManager.GetString("_MobilePhone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        internal static string _MoveBtn {
            get {
                return ResourceManager.GetString("_MoveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Supervisor.
        /// </summary>
        internal static string _NewSupervisor {
            get {
                return ResourceManager.GetString("_NewSupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string _Notes {
            get {
                return ResourceManager.GetString("_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure download this template?.
        /// </summary>
        internal static string _NotifDownloadTemplate {
            get {
                return ResourceManager.GetString("_NotifDownloadTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Supervisor and New Supervisor Can&apos;t be the same!!!.
        /// </summary>
        internal static string _NotifDulticateOldAndNew {
            get {
                return ResourceManager.GetString("_NotifDulticateOldAndNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to import data?.
        /// </summary>
        internal static string _NotifImportData {
            get {
                return ResourceManager.GetString("_NotifImportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure {0} Staff {1}?.
        /// </summary>
        internal static string _NotifInactive {
            get {
                return ResourceManager.GetString("_NotifInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to process!!!.
        /// </summary>
        internal static string _NotifNoProcessData {
            get {
                return ResourceManager.GetString("_NotifNoProcessData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff department will be replacing with department from New Supervisor, are you want to process?.
        /// </summary>
        internal static string _NotifReplaceOldToNew {
            get {
                return ResourceManager.GetString("_NotifReplaceOldToNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff move successfully!.
        /// </summary>
        internal static string _NotifSuccessMove {
            get {
                return ResourceManager.GetString("_NotifSuccessMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff uploaded successfully!.
        /// </summary>
        internal static string _NotifSuccessUpload {
            get {
                return ResourceManager.GetString("_NotifSuccessUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Supervisor.
        /// </summary>
        internal static string _OldSupervisor {
            get {
                return ResourceManager.GetString("_OldSupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string _Position {
            get {
                return ResourceManager.GetString("_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        internal static string _ProcessBtn {
            get {
                return ResourceManager.GetString("_ProcessBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string _Property {
            get {
                return ResourceManager.GetString("_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string _SaveBtn {
            get {
                return ResourceManager.GetString("_SaveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save To Excel.
        /// </summary>
        internal static string _SaveToExcelBtn {
            get {
                return ResourceManager.GetString("_SaveToExcelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source File.
        /// </summary>
        internal static string _SourceFile {
            get {
                return ResourceManager.GetString("_SourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Id.
        /// </summary>
        internal static string _StaffId {
            get {
                return ResourceManager.GetString("_StaffId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Name.
        /// </summary>
        internal static string _StaffName {
            get {
                return ResourceManager.GetString("_StaffName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string _State {
            get {
                return ResourceManager.GetString("_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string _Status {
            get {
                return ResourceManager.GetString("_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor.
        /// </summary>
        internal static string _Supervisor {
            get {
                return ResourceManager.GetString("_Supervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor Id.
        /// </summary>
        internal static string _SupervisorId {
            get {
                return ResourceManager.GetString("_SupervisorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        internal static string _TemplateBtn {
            get {
                return ResourceManager.GetString("_TemplateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Row(s).
        /// </summary>
        internal static string _TotalRow {
            get {
                return ResourceManager.GetString("_TotalRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated By.
        /// </summary>
        internal static string _UpdateBy {
            get {
                return ResourceManager.GetString("_UpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Date.
        /// </summary>
        internal static string _UpdateDate {
            get {
                return ResourceManager.GetString("_UpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string _UploadBtn {
            get {
                return ResourceManager.GetString("_UploadBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        internal static string _Valid {
            get {
                return ResourceManager.GetString("_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        internal static string _ZipCode {
            get {
                return ResourceManager.GetString("_ZipCode", resourceCulture);
            }
        }
    }
}
