//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GLB09900FrontResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GLB09900FrontResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GLB09900FrontResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GLB09900FrontResources.GLB09900FrontResources_msgrsc", typeof(GLB09900FrontResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string _CancelBtn {
            get {
                return ResourceManager.GetString("_CancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Period.
        /// </summary>
        internal static string _CurrentPeriod {
            get {
                return ResourceManager.GetString("_CurrentPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Period End process will disable journal posting and changes for the current period and cannot be reopened!.
        /// </summary>
        internal static string _Desc1ClosePeriod {
            get {
                return ResourceManager.GetString("_Desc1ClosePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure that all journals have been posted and checked..
        /// </summary>
        internal static string _Desc2ClosePeriod {
            get {
                return ResourceManager.GetString("_Desc2ClosePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DO BACK UP your data before running this process!.
        /// </summary>
        internal static string _Desc3ClosePeriod {
            get {
                return ResourceManager.GetString("_Desc3ClosePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to proceed with Period-End Closing?.
        /// </summary>
        internal static string _NotifAlertClosePeiod {
            get {
                return ResourceManager.GetString("_NotifAlertClosePeiod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soft Close GL Period should be done prior to Close GL Period.
        /// </summary>
        internal static string _NotifErrorSoftClose {
            get {
                return ResourceManager.GetString("_NotifErrorSoftClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period End.
        /// </summary>
        internal static string _ProcessBtn {
            get {
                return ResourceManager.GetString("_ProcessBtn", resourceCulture);
            }
        }
    }
}
