using System;
using System.Collections.Generic;
using System.Text;

namespace LMM04000COMMON
{
    public class ContextConstant
    {
        public const string LMM04000_PROPERTY_ID_STREAMING_CONTEXT = "LMM04000_PROPERTY_ID_STREAMING_CONTEXT";

        public const string LMM04010_PROPERTY_ID_STREAMING_CONTEXT = "LMM04010_PROPERTY_ID_STREAMING_CONTEXT";
        public const string LMM04010_PROPERTY_ID_CONTEXT = "LMM04010_PROPERTY_ID_CONTEXT";
        public const string LMM04010_TENANT_ID_CONTEXT = "LMM04010_TENANT_ID_CONTEXT";

        public const string LMM04020_PROPERTY_ID_CONTEXT = "LMM04020_PROPERTY_ID_CONTEXT";
        public const string LMM04020_TENANT_ID_CONTEXT = "LMM04020_TENANT_ID_CONTEXT";

        public const string LMM04030_PROPERTY_ID_STREAMING_CONTEXT = "LMM04030_PROPERTY_ID_STREAMING_CONTEXT";
        public const string LMM04030_TENANT_ID_STREAMING_CONTEXT = "LMM04030_TENANT_ID_STREAMING_CONTEXT";
        public const string LMM04030_PROPERTY_ID_CONTEXT = "LMM04030_PROPERTY_ID_CONTEXT";
        public const string LMM04030_TENANT_ID_CONTEXT = "LMM04030_TENANT_ID_CONTEXT";

        public const string UPLOAD_CONTRACTOR_PROPERTY_ID_CONTEXT = "UPLOAD_CONTRACTOR_PROPERTY_ID_CONTEXT";
        public const string UPLOAD_CONTRACTOR_IS_OVERWRITE_CONTEXT = "UPLOAD_CONTRACTOR_IS_OVERWRITE_CONTEXT";
        public const string UPLOAD_CONTRACTOR_STREAMING_CONTEXT = "UPLOAD_CONTRACTOR_STREAMING_CONTEXT";
        public const string UPLOAD_CONTRACTOR_ERROR_GUID_STREAMING_CONTEXT = "UPLOAD_CONTRACTOR_ERROR_GUID_STREAMING_CONTEXT";
    }
}
