using System;
using System.Collections.Generic;
using System.Text;

namespace GSM07000COMMON.DTOs
{
    public class ContextConstant
    {
        public const string SELECTED_APPROVAL_CODE_STREAMING_CONTEXT = "SELECTED_APPROVAL_CODE_STREAMING_CONTEXT";
        public const string SELECTED_APPROVAL_CODE_CONTEXT = "SELECTED_APPROVAL_CODE_CONTEXT";
        public const string SELECTED_USER_ID_CONTEXT = "SELECTED_APPROVAL_CODE_STREAMING_CONTEXT";
        public const string GSM07011_CAPPROVAL_CODE_STREAMING_CONTEXT = "GSM07011_CAPPROVAL_CODE_STREAMING_CONTEXT";
        public const string GSM07011_SELECTED_APPROVAL_CODE_CONTEXT = "GSM07011_SELECTED_APPROVAL_CODE_CONTEXT";
        public const string GSM07011_SELECTED_USER_ID_CONTEXT = "GSM07011_SELECTED_USER_ID_CONTEXT";
    }
}
