//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APT00600FrontResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class APT00600FrontResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal APT00600FrontResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("APT00600FrontResources.APT00600FrontResources_msgrsc", typeof(APT00600FrontResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocation Amount.
        /// </summary>
        internal static string _AllocAmount {
            get {
                return ResourceManager.GetString("_AllocAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocate.
        /// </summary>
        internal static string _Allocate {
            get {
                return ResourceManager.GetString("_Allocate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocation.
        /// </summary>
        internal static string _Allocation {
            get {
                return ResourceManager.GetString("_Allocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocation Detail.
        /// </summary>
        internal static string _AllocationDetail {
            get {
                return ResourceManager.GetString("_AllocationDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocation ID.
        /// </summary>
        internal static string _AllocationID {
            get {
                return ResourceManager.GetString("_AllocationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alloc. Ref. No..
        /// </summary>
        internal static string _AllocRefNo {
            get {
                return ResourceManager.GetString("_AllocRefNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alloc. Trx Ref. No..
        /// </summary>
        internal static string _AllocTrxRefNo {
            get {
                return ResourceManager.GetString("_AllocTrxRefNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alloc. Trx Type.
        /// </summary>
        internal static string _AllocTrxType {
            get {
                return ResourceManager.GetString("_AllocTrxType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Suppliers.
        /// </summary>
        internal static string _AllSuppliers {
            get {
                return ResourceManager.GetString("_AllSuppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string _Amount {
            get {
                return ResourceManager.GetString("_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount (Base).
        /// </summary>
        internal static string _Amount_Base_ {
            get {
                return ResourceManager.GetString("_Amount(Base)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount (Local).
        /// </summary>
        internal static string _Amount_Local_ {
            get {
                return ResourceManager.GetString("_Amount(Local)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount (Trx).
        /// </summary>
        internal static string _Amount_Trx_ {
            get {
                return ResourceManager.GetString("_Amount(Trx)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Qty.
        /// </summary>
        internal static string _ApprovedQty {
            get {
                return ResourceManager.GetString("_ApprovedQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        internal static string _Base {
            get {
                return ResourceManager.GetString("_Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Currency.
        /// </summary>
        internal static string _BaseCurrency {
            get {
                return ResourceManager.GetString("_BaseCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CF.
        /// </summary>
        internal static string _CF {
            get {
                return ResourceManager.GetString("_CF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge Dept..
        /// </summary>
        internal static string _ChargeDept {
            get {
                return ResourceManager.GetString("_ChargeDept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge ID.
        /// </summary>
        internal static string _ChargeID {
            get {
                return ResourceManager.GetString("_ChargeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge Name.
        /// </summary>
        internal static string _ChargeName {
            get {
                return ResourceManager.GetString("_ChargeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string _Close {
            get {
                return ResourceManager.GetString("_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        internal static string _CreatedBy {
            get {
                return ResourceManager.GetString("_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        internal static string _CreatedDate {
            get {
                return ResourceManager.GetString("_CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curr..
        /// </summary>
        internal static string _Curr {
            get {
                return ResourceManager.GetString("_Curr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string _Currency {
            get {
                return ResourceManager.GetString("_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Rate.
        /// </summary>
        internal static string _CurrencyRate {
            get {
                return ResourceManager.GetString("_CurrencyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string _Date {
            get {
                return ResourceManager.GetString("_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Adjustment Entry.
        /// </summary>
        internal static string _DebitAdjEntry {
            get {
                return ResourceManager.GetString("_DebitAdjEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deduction.
        /// </summary>
        internal static string _Deduction {
            get {
                return ResourceManager.GetString("_Deduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string _Department {
            get {
                return ResourceManager.GetString("_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dept. Code.
        /// </summary>
        internal static string _DeptCode {
            get {
                return ResourceManager.GetString("_DeptCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dept. Name.
        /// </summary>
        internal static string _DeptName {
            get {
                return ResourceManager.GetString("_DeptName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string _Desc {
            get {
                return ResourceManager.GetString("_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string _Description {
            get {
                return ResourceManager.GetString("_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string _Detail {
            get {
                return ResourceManager.GetString("_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        internal static string _Draft {
            get {
                return ResourceManager.GetString("_Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Entry.
        /// </summary>
        internal static string _ItemEntry {
            get {
                return ResourceManager.GetString("_ItemEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item List.
        /// </summary>
        internal static string _ItemList {
            get {
                return ResourceManager.GetString("_ItemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal.
        /// </summary>
        internal static string _Journal {
            get {
                return ResourceManager.GetString("_Journal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Amount.
        /// </summary>
        internal static string _LineAmount {
            get {
                return ResourceManager.GetString("_LineAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Discount.
        /// </summary>
        internal static string _LineDiscount {
            get {
                return ResourceManager.GetString("_LineDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        internal static string _Local {
            get {
                return ResourceManager.GetString("_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Amount.
        /// </summary>
        internal static string _LocalAmount {
            get {
                return ResourceManager.GetString("_LocalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Currency.
        /// </summary>
        internal static string _LocalCurrency {
            get {
                return ResourceManager.GetString("_LocalCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to delete this Purchase Debit Adjustment?.
        /// </summary>
        internal static string _N001 {
            get {
                return ResourceManager.GetString("_N001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven’t saved your changes. Are you sure want to cancel?.
        /// </summary>
        internal static string _N002 {
            get {
                return ResourceManager.GetString("_N002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to submit this Purchase Debit Adjustment?.
        /// </summary>
        internal static string _N003 {
            get {
                return ResourceManager.GetString("_N003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to redraft this Purchase Debit Adjustment?.
        /// </summary>
        internal static string _N004 {
            get {
                return ResourceManager.GetString("_N004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Amount.
        /// </summary>
        internal static string _NetAmount {
            get {
                return ResourceManager.GetString("_NetAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string _No {
            get {
                return ResourceManager.GetString("_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string _Notes {
            get {
                return ResourceManager.GetString("_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Tax.
        /// </summary>
        internal static string _OtherTax {
            get {
                return ResourceManager.GetString("_OtherTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period From.
        /// </summary>
        internal static string _PeriodFrom {
            get {
                return ResourceManager.GetString("_PeriodFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string _Property {
            get {
                return ResourceManager.GetString("_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Amount.
        /// </summary>
        internal static string _PurchaseAmount {
            get {
                return ResourceManager.GetString("_PurchaseAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Qty.
        /// </summary>
        internal static string _PurchaseQty {
            get {
                return ResourceManager.GetString("_PurchaseQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        internal static string _Qty {
            get {
                return ResourceManager.GetString("_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redraft.
        /// </summary>
        internal static string _Redraft {
            get {
                return ResourceManager.GetString("_Redraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref. Date.
        /// </summary>
        internal static string _RefDate {
            get {
                return ResourceManager.GetString("_RefDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference No.
        /// </summary>
        internal static string _ReferenceNo {
            get {
                return ResourceManager.GetString("_ReferenceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref. No..
        /// </summary>
        internal static string _RefNo {
            get {
                return ResourceManager.GetString("_RefNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string _Refresh {
            get {
                return ResourceManager.GetString("_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining.
        /// </summary>
        internal static string _Remaining {
            get {
                return ResourceManager.GetString("_Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Suppliers.
        /// </summary>
        internal static string _SelectedSuppliers {
            get {
                return ResourceManager.GetString("_SelectedSuppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seq No..
        /// </summary>
        internal static string _SeqNo {
            get {
                return ResourceManager.GetString("_SeqNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string _Status {
            get {
                return ResourceManager.GetString("_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string _Submit {
            get {
                return ResourceManager.GetString("_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        internal static string _Supplier {
            get {
                return ResourceManager.GetString("_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        internal static string _Tax {
            get {
                return ResourceManager.GetString("_Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Amount.
        /// </summary>
        internal static string _TaxAmount {
            get {
                return ResourceManager.GetString("_TaxAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Rate.
        /// </summary>
        internal static string _TaxRate {
            get {
                return ResourceManager.GetString("_TaxRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term.
        /// </summary>
        internal static string _Term {
            get {
                return ResourceManager.GetString("_Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        internal static string _to {
            get {
                return ResourceManager.GetString("_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Adjustment Amount.
        /// </summary>
        internal static string _totalAdjAmount {
            get {
                return ResourceManager.GetString("_totalAdjAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Remaining.
        /// </summary>
        internal static string _TotalRemaining {
            get {
                return ResourceManager.GetString("_TotalRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction.
        /// </summary>
        internal static string _Transaction {
            get {
                return ResourceManager.GetString("_Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Type.
        /// </summary>
        internal static string _TransactionType {
            get {
                return ResourceManager.GetString("_TransactionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trx Amount.
        /// </summary>
        internal static string _TrxAmount {
            get {
                return ResourceManager.GetString("_TrxAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string _Type {
            get {
                return ResourceManager.GetString("_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string _Unit {
            get {
                return ResourceManager.GetString("_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        internal static string _UnitPrice {
            get {
                return ResourceManager.GetString("_UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated By.
        /// </summary>
        internal static string _UpdatedBy {
            get {
                return ResourceManager.GetString("_UpdatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Date.
        /// </summary>
        internal static string _UpdatedDate {
            get {
                return ResourceManager.GetString("_UpdatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Department!.
        /// </summary>
        internal static string V001 {
            get {
                return ResourceManager.GetString("V001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Supplier!.
        /// </summary>
        internal static string V002 {
            get {
                return ResourceManager.GetString("V002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select property!.
        /// </summary>
        internal static string V003 {
            get {
                return ResourceManager.GetString("V003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select department!.
        /// </summary>
        internal static string V004 {
            get {
                return ResourceManager.GetString("V004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref. Date is required!.
        /// </summary>
        internal static string V005 {
            get {
                return ResourceManager.GetString("V005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref. Date cannot be before Soft Close Period!.
        /// </summary>
        internal static string V006 {
            get {
                return ResourceManager.GetString("V006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Supplier!.
        /// </summary>
        internal static string V007 {
            get {
                return ResourceManager.GetString("V007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Supplier Sequence No..
        /// </summary>
        internal static string V008 {
            get {
                return ResourceManager.GetString("V008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required!.
        /// </summary>
        internal static string V009 {
            get {
                return ResourceManager.GetString("V009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Transaction Type!.
        /// </summary>
        internal static string V010 {
            get {
                return ResourceManager.GetString("V010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference No. is required!.
        /// </summary>
        internal static string V011 {
            get {
                return ResourceManager.GetString("V011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount cannot be greater than Remaining Amount!.
        /// </summary>
        internal static string V012 {
            get {
                return ResourceManager.GetString("V012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Amount cannot be greater than Remaining Tax Amount!.
        /// </summary>
        internal static string V013 {
            get {
                return ResourceManager.GetString("V013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocation Amount cannot be 0!.
        /// </summary>
        internal static string V014 {
            get {
                return ResourceManager.GetString("V014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Charge Dept.!.
        /// </summary>
        internal static string V015 {
            get {
                return ResourceManager.GetString("V015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Charge ID!.
        /// </summary>
        internal static string V016 {
            get {
                return ResourceManager.GetString("V016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot process Purchase Debit Adjustment with Manual Numbering! Transaction numbering setting for Purchase Debit Adjustment should be auto increment, not manual numbering!.
        /// </summary>
        internal static string V036 {
            get {
                return ResourceManager.GetString("V036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot process Allocation with Manual Numbering! Transaction numbering setting for Allocation should be auto increment, not manual numbering!.
        /// </summary>
        internal static string V037 {
            get {
                return ResourceManager.GetString("V037", resourceCulture);
            }
        }
    }
}
