//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMM07000FrontResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LMM07000FrontResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LMM07000FrontResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LMM07000FrontResources.LMM07000FrontResources_msgrsc", typeof(LMM07000FrontResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Code is required.
        /// </summary>
        internal static string _7010 {
            get {
                return ResourceManager.GetString("7010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Code Maximum 20 Character.
        /// </summary>
        internal static string _7011 {
            get {
                return ResourceManager.GetString("7011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Name is required.
        /// </summary>
        internal static string _7012 {
            get {
                return ResourceManager.GetString("7012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Name Maximum 100 Character.
        /// </summary>
        internal static string _7013 {
            get {
                return ResourceManager.GetString("7013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount type is required.
        /// </summary>
        internal static string _7014 {
            get {
                return ResourceManager.GetString("7014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Value must greater than 0.
        /// </summary>
        internal static string _7015 {
            get {
                return ResourceManager.GetString("7015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Value must greater than 0 and less than 100.
        /// </summary>
        internal static string _7016 {
            get {
                return ResourceManager.GetString("7016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Period From and Invoice Period To is required.
        /// </summary>
        internal static string _7017 {
            get {
                return ResourceManager.GetString("7017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Period To must greater or equal to Invoice Period From.
        /// </summary>
        internal static string _7018 {
            get {
                return ResourceManager.GetString("7018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Period From Value must between of 1 and {0}.
        /// </summary>
        internal static string _7019 {
            get {
                return ResourceManager.GetString("7019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Period To Value must between of 1 and {0}.
        /// </summary>
        internal static string _7020 {
            get {
                return ResourceManager.GetString("7020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string _Active {
            get {
                return ResourceManager.GetString("_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string _CancelBtn {
            get {
                return ResourceManager.GetString("_CancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges Type.
        /// </summary>
        internal static string _ChargesType {
            get {
                return ResourceManager.GetString("_ChargesType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        internal static string _CreateBy {
            get {
                return ResourceManager.GetString("_CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        internal static string _CreateDate {
            get {
                return ResourceManager.GetString("_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string _Desc {
            get {
                return ResourceManager.GetString("_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Code.
        /// </summary>
        internal static string _DiscCode {
            get {
                return ResourceManager.GetString("_DiscCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Name.
        /// </summary>
        internal static string _DiscName {
            get {
                return ResourceManager.GetString("_DiscName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Type.
        /// </summary>
        internal static string _Disctype {
            get {
                return ResourceManager.GetString("_Disctype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Value.
        /// </summary>
        internal static string _DiscVal {
            get {
                return ResourceManager.GetString("_DiscVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Period From.
        /// </summary>
        internal static string _InvPeriodFrom {
            get {
                return ResourceManager.GetString("_InvPeriodFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Period To.
        /// </summary>
        internal static string _InvPeriodTo {
            get {
                return ResourceManager.GetString("_InvPeriodTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure {0} {1}?.
        /// </summary>
        internal static string _NotifInactive {
            get {
                return ResourceManager.GetString("_NotifInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        internal static string _ProcessBtn {
            get {
                return ResourceManager.GetString("_ProcessBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string _Property {
            get {
                return ResourceManager.GetString("_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string _Status {
            get {
                return ResourceManager.GetString("_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string _To {
            get {
                return ResourceManager.GetString("_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated By.
        /// </summary>
        internal static string _UpdateBy {
            get {
                return ResourceManager.GetString("_UpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Date.
        /// </summary>
        internal static string _UpdateDate {
            get {
                return ResourceManager.GetString("_UpdateDate", resourceCulture);
            }
        }
    }
}
