//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSM02200FrontResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GSM02200FrontResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GSM02200FrontResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GSM02200FrontResources.GSM02200FrontResources_msgrsc", typeof(GSM02200FrontResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should fill Geography Code.
        /// </summary>
        internal static string _2204 {
            get {
                return ResourceManager.GetString("2204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should fill Geography Description.
        /// </summary>
        internal static string _2205 {
            get {
                return ResourceManager.GetString("2205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geography Code Maximum 20 Character.
        /// </summary>
        internal static string _2206 {
            get {
                return ResourceManager.GetString("2206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geography Name Maximum 200 Character.
        /// </summary>
        internal static string _2207 {
            get {
                return ResourceManager.GetString("2207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string _Active {
            get {
                return ResourceManager.GetString("_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string _CancelBtn {
            get {
                return ResourceManager.GetString("_CancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        internal static string _CreateBy {
            get {
                return ResourceManager.GetString("_CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        internal static string _CreateDate {
            get {
                return ResourceManager.GetString("_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geography Code.
        /// </summary>
        internal static string _GeoCode {
            get {
                return ResourceManager.GetString("_GeoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geography Description.
        /// </summary>
        internal static string _GeoDesc {
            get {
                return ResourceManager.GetString("_GeoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geography Name.
        /// </summary>
        internal static string _GeoName {
            get {
                return ResourceManager.GetString("_GeoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        internal static string _Invalid {
            get {
                return ResourceManager.GetString("_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string _Notes {
            get {
                return ResourceManager.GetString("_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure {0} this?.
        /// </summary>
        internal static string _NotifActiveInactive {
            get {
                return ResourceManager.GetString("_NotifActiveInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to import data?.
        /// </summary>
        internal static string _NotifImportData {
            get {
                return ResourceManager.GetString("_NotifImportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff uploaded successfully!.
        /// </summary>
        internal static string _NotifSuccesUpload {
            get {
                return ResourceManager.GetString("_NotifSuccesUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure download this template?.
        /// </summary>
        internal static string _NotifTemplate {
            get {
                return ResourceManager.GetString("_NotifTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Code.
        /// </summary>
        internal static string _ParentCode {
            get {
                return ResourceManager.GetString("_ParentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Description.
        /// </summary>
        internal static string _ParentDesc {
            get {
                return ResourceManager.GetString("_ParentDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Name.
        /// </summary>
        internal static string _ParentName {
            get {
                return ResourceManager.GetString("_ParentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string _PrintBtn {
            get {
                return ResourceManager.GetString("_PrintBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        internal static string _ProcessBtn {
            get {
                return ResourceManager.GetString("_ProcessBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref Code.
        /// </summary>
        internal static string _RefCode {
            get {
                return ResourceManager.GetString("_RefCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save To Excel.
        /// </summary>
        internal static string _SaveToExcelBtn {
            get {
                return ResourceManager.GetString("_SaveToExcelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Inactive Geography.
        /// </summary>
        internal static string _ShowInactiveGeo {
            get {
                return ResourceManager.GetString("_ShowInactiveGeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string _Status {
            get {
                return ResourceManager.GetString("_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        internal static string _TemplateBtn {
            get {
                return ResourceManager.GetString("_TemplateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Row(s).
        /// </summary>
        internal static string _TotalProcess {
            get {
                return ResourceManager.GetString("_TotalProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated By.
        /// </summary>
        internal static string _UpdateBy {
            get {
                return ResourceManager.GetString("_UpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Date.
        /// </summary>
        internal static string _UpdateDate {
            get {
                return ResourceManager.GetString("_UpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string _UploadBtn {
            get {
                return ResourceManager.GetString("_UploadBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        internal static string _Valid {
            get {
                return ResourceManager.GetString("_Valid", resourceCulture);
            }
        }
    }
}
