using System;
using System.Collections.Generic;
using System.Text;

namespace GSM09300COMMON
{
    public class ContextConstant
    {
        public const string GSM09300_PROPERTY_ID_CONTEXT = "GSM09300_PROPERTY_ID_CONTEXT";
        public const string GSM09300_PROPERTY_ID_STREAMING_CONTEXT = "GSM09300_PROPERTY_ID_STREAMING_CONTEXT";

        public const string GSM09310_PROPERTY_ID_CONTEXT = "GSM09310_PROPERTY_ID_CONTEXT";
        public const string GSM09310_SUPPLIER_ID_CONTEXT = "GSM09310_SUPPLIER_ID_CONTEXT";
        public const string GSM09310_FROM_SUPPLIER_CATEGORY_ID_CONTEXT = "GSM09310_FROM_SUPPLIER_CATEGORY_ID_CONTEXT";
        public const string GSM09310_FROM_SUPPLIER_CATEGORY_ID_STREAMING_CONTEXT = "GSM09310_FROM_SUPPLIER_CATEGORY_ID_STREAMING_CONTEXT";
        public const string GSM09310_SUPPLIER_CATEGORY_ID_CONTEXT = "GSM09310_SUPPLIER_CATEGORY_ID_CONTEXT";
        public const string GSM09310_TO_SUPPLIER_CATEGORY_ID_CONTEXT = "GSM09310_TO_SUPPLIER_CATEGORY_ID_CONTEXT";
        public const string GSM09310_PROPERTY_ID_STREAMING_CONTEXT = "GSM09310_PROPERTY_ID_STREAMING_CONTEXT";

    }
}
