//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APT00300FrontResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class APT00300FrontResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal APT00300FrontResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("APT00300FrontResources.APT00300FrontResources_msgrsc", typeof(APT00300FrontResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string _Active {
            get {
                return ResourceManager.GetString("_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addition.
        /// </summary>
        internal static string _Addition {
            get {
                return ResourceManager.GetString("_Addition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add On.
        /// </summary>
        internal static string _AddOn {
            get {
                return ResourceManager.GetString("_AddOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocate.
        /// </summary>
        internal static string _Allocate {
            get {
                return ResourceManager.GetString("_Allocate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocation ID.
        /// </summary>
        internal static string _AllocID {
            get {
                return ResourceManager.GetString("_AllocID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string _Amount {
            get {
                return ResourceManager.GetString("_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        internal static string _Approve {
            get {
                return ResourceManager.GetString("_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base .
        /// </summary>
        internal static string _Base {
            get {
                return ResourceManager.GetString("_Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string _BtnDetail {
            get {
                return ResourceManager.GetString("_BtnDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal.
        /// </summary>
        internal static string _BtnJournal {
            get {
                return ResourceManager.GetString("_BtnJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string _BtnPrint {
            get {
                return ResourceManager.GetString("_BtnPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redraft.
        /// </summary>
        internal static string _BtnRedraft {
            get {
                return ResourceManager.GetString("_BtnRedraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string _BtnSubmit {
            get {
                return ResourceManager.GetString("_BtnSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string _CancelBtn {
            get {
                return ResourceManager.GetString("_CancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string _Category {
            get {
                return ResourceManager.GetString("_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string _Close {
            get {
                return ResourceManager.GetString("_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        internal static string _CreateBy {
            get {
                return ResourceManager.GetString("_CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        internal static string _CreateDate {
            get {
                return ResourceManager.GetString("_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curr..
        /// </summary>
        internal static string _Curr {
            get {
                return ResourceManager.GetString("_Curr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency .
        /// </summary>
        internal static string _Currency {
            get {
                return ResourceManager.GetString("_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string _Date {
            get {
                return ResourceManager.GetString("_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deduction.
        /// </summary>
        internal static string _Deducation {
            get {
                return ResourceManager.GetString("_Deducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string _Dept {
            get {
                return ResourceManager.GetString("_Dept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string _Desc {
            get {
                return ResourceManager.GetString("_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        internal static string _Disc {
            get {
                return ResourceManager.GetString("_Disc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        internal static string _DueDate {
            get {
                return ResourceManager.GetString("_DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenditure.
        /// </summary>
        internal static string _Expen {
            get {
                return ResourceManager.GetString("_Expen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string _From {
            get {
                return ResourceManager.GetString("_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Entry.
        /// </summary>
        internal static string _InvEntry {
            get {
                return ResourceManager.GetString("_InvEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Header.
        /// </summary>
        internal static string _InvHeader {
            get {
                return ResourceManager.GetString("_InvHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Amount.
        /// </summary>
        internal static string _LineAmount {
            get {
                return ResourceManager.GetString("_LineAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Discount.
        /// </summary>
        internal static string _LineDisc {
            get {
                return ResourceManager.GetString("_LineDisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local .
        /// </summary>
        internal static string _Local {
            get {
                return ResourceManager.GetString("_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Local Amount).
        /// </summary>
        internal static string _LocalAmount {
            get {
                return ResourceManager.GetString("_LocalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Amount.
        /// </summary>
        internal static string _NetAmount {
            get {
                return ResourceManager.GetString("_NetAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string _Notes {
            get {
                return ResourceManager.GetString("_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot process Purchase Debit Note with Manual Numbering! Transaction numbering setting for Purchase Debit Note should be auto increment, not manual numbering!.
        /// </summary>
        internal static string _NotifyIncrementFlag {
            get {
                return ResourceManager.GetString("_NotifyIncrementFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string _OkBtn {
            get {
                return ResourceManager.GetString("_OkBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Time.
        /// </summary>
        internal static string _OneTime {
            get {
                return ResourceManager.GetString("_OneTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string _Other {
            get {
                return ResourceManager.GetString("_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        internal static string _Period {
            get {
                return ResourceManager.GetString("_Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string _Price {
            get {
                return ResourceManager.GetString("_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        internal static string _ProcessBtn {
            get {
                return ResourceManager.GetString("_ProcessBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string _Product {
            get {
                return ResourceManager.GetString("_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Dept..
        /// </summary>
        internal static string _ProductDept {
            get {
                return ResourceManager.GetString("_ProductDept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product/Expenditure.
        /// </summary>
        internal static string _ProductExpen {
            get {
                return ResourceManager.GetString("_ProductExpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product ID.
        /// </summary>
        internal static string _ProductID {
            get {
                return ResourceManager.GetString("_ProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        internal static string _ProductName {
            get {
                return ResourceManager.GetString("_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Type*.
        /// </summary>
        internal static string _ProductType {
            get {
                return ResourceManager.GetString("_ProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string _Property {
            get {
                return ResourceManager.GetString("_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase .
        /// </summary>
        internal static string _Purchase {
            get {
                return ResourceManager.GetString("_Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qyt.
        /// </summary>
        internal static string _Qyt {
            get {
                return ResourceManager.GetString("_Qyt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        internal static string _Rate {
            get {
                return ResourceManager.GetString("_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref Date.
        /// </summary>
        internal static string _RefDate {
            get {
                return ResourceManager.GetString("_RefDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference No..
        /// </summary>
        internal static string _ReferenceNo {
            get {
                return ResourceManager.GetString("_ReferenceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref No.
        /// </summary>
        internal static string _RefNo {
            get {
                return ResourceManager.GetString("_RefNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string _Refresh {
            get {
                return ResourceManager.GetString("_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string _Save {
            get {
                return ResourceManager.GetString("_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seq No..
        /// </summary>
        internal static string _SeqNo {
            get {
                return ResourceManager.GetString("_SeqNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string _Status {
            get {
                return ResourceManager.GetString("_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string _Summary {
            get {
                return ResourceManager.GetString("_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier .
        /// </summary>
        internal static string _Supp {
            get {
                return ResourceManager.GetString("_Supp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier ID.
        /// </summary>
        internal static string _SuppId {
            get {
                return ResourceManager.GetString("_SuppId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier ID / Name*.
        /// </summary>
        internal static string _SuppIdName {
            get {
                return ResourceManager.GetString("_SuppIdName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Suppliers.
        /// </summary>
        internal static string _SuppModeA {
            get {
                return ResourceManager.GetString("_SuppModeA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Supplier.
        /// </summary>
        internal static string _SuppModeS {
            get {
                return ResourceManager.GetString("_SuppModeS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier&apos;s Product*.
        /// </summary>
        internal static string _SuppProduct {
            get {
                return ResourceManager.GetString("_SuppProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier&apos;s Ref No..
        /// </summary>
        internal static string _SuppRefNo {
            get {
                return ResourceManager.GetString("_SuppRefNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Status.
        /// </summary>
        internal static string _SuppStatus {
            get {
                return ResourceManager.GetString("_SuppStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Item.
        /// </summary>
        internal static string _TabInvItem {
            get {
                return ResourceManager.GetString("_TabInvItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        internal static string _Tax {
            get {
                return ResourceManager.GetString("_Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxable.
        /// </summary>
        internal static string _Taxable {
            get {
                return ResourceManager.GetString("_Taxable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Trx Amount).
        /// </summary>
        internal static string _TaxDesc {
            get {
                return ResourceManager.GetString("_TaxDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Rate.
        /// </summary>
        internal static string _TaxRate {
            get {
                return ResourceManager.GetString("_TaxRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term.
        /// </summary>
        internal static string _Term {
            get {
                return ResourceManager.GetString("_Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string _To {
            get {
                return ResourceManager.GetString("_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total .
        /// </summary>
        internal static string _Total {
            get {
                return ResourceManager.GetString("_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string _Type {
            get {
                return ResourceManager.GetString("_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string _Unit {
            get {
                return ResourceManager.GetString("_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated By.
        /// </summary>
        internal static string _UpdateBy {
            get {
                return ResourceManager.GetString("_UpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Date.
        /// </summary>
        internal static string _UpdateDate {
            get {
                return ResourceManager.GetString("_UpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Department!.
        /// </summary>
        internal static string Err01 {
            get {
                return ResourceManager.GetString("Err01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Supplier!.
        /// </summary>
        internal static string Err02 {
            get {
                return ResourceManager.GetString("Err02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period Year From or Period Year To must between of {0} and {1}.
        /// </summary>
        internal static string Err03 {
            get {
                return ResourceManager.GetString("Err03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select property!.
        /// </summary>
        internal static string Err04 {
            get {
                return ResourceManager.GetString("Err04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Name is required!.
        /// </summary>
        internal static string Err05 {
            get {
                return ResourceManager.GetString("Err05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document No. is required!.
        /// </summary>
        internal static string Err06 {
            get {
                return ResourceManager.GetString("Err06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Date is required!.
        /// </summary>
        internal static string Err07 {
            get {
                return ResourceManager.GetString("Err07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select term!.
        /// </summary>
        internal static string Err08 {
            get {
                return ResourceManager.GetString("Err08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select currency!.
        /// </summary>
        internal static string Err09 {
            get {
                return ResourceManager.GetString("Err09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Currency Base Rate must be greater than 0!.
        /// </summary>
        internal static string Err10 {
            get {
                return ResourceManager.GetString("Err10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Currency Rate must be greater than 0!.
        /// </summary>
        internal static string Err11 {
            get {
                return ResourceManager.GetString("Err11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Currency Base Rate must be greater than 0!.
        /// </summary>
        internal static string Err12 {
            get {
                return ResourceManager.GetString("Err12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Currency Rate must be greater than 0!.
        /// </summary>
        internal static string Err13 {
            get {
                return ResourceManager.GetString("Err13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Tax ID!.
        /// </summary>
        internal static string Err14 {
            get {
                return ResourceManager.GetString("Err14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Base Rate must be greater than 0!.
        /// </summary>
        internal static string Err15 {
            get {
                return ResourceManager.GetString("Err15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Rate must be greater than 0!.
        /// </summary>
        internal static string Err16 {
            get {
                return ResourceManager.GetString("Err16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required!.
        /// </summary>
        internal static string Err17 {
            get {
                return ResourceManager.GetString("Err17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Date is required!.
        /// </summary>
        internal static string Err18 {
            get {
                return ResourceManager.GetString("Err18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Product Department!.
        /// </summary>
        internal static string Err19 {
            get {
                return ResourceManager.GetString("Err19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Product Type!.
        /// </summary>
        internal static string Err20 {
            get {
                return ResourceManager.GetString("Err20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Product!.
        /// </summary>
        internal static string Err21 {
            get {
                return ResourceManager.GetString("Err21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Expenditure!.
        /// </summary>
        internal static string Err22 {
            get {
                return ResourceManager.GetString("Err22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Allocation ID!.
        /// </summary>
        internal static string Err23 {
            get {
                return ResourceManager.GetString("Err23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit Qty must be &gt; 0!.
        /// </summary>
        internal static string Err24 {
            get {
                return ResourceManager.GetString("Err24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Unit!.
        /// </summary>
        internal static string Err25 {
            get {
                return ResourceManager.GetString("Err25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Unit is required!.
        /// </summary>
        internal static string Err26 {
            get {
                return ResourceManager.GetString("Err26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion Factor must be &gt; 0!.
        /// </summary>
        internal static string Err27 {
            get {
                return ResourceManager.GetString("Err27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price must be &gt; 0.
        /// </summary>
        internal static string Err28 {
            get {
                return ResourceManager.GetString("Err28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Discount Percentage! Please input value between 0 and 100..
        /// </summary>
        internal static string Err29 {
            get {
                return ResourceManager.GetString("Err29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Amount cannot be &lt; 0!.
        /// </summary>
        internal static string Err30 {
            get {
                return ResourceManager.GetString("Err30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Discount Amount! Discount Amount cannot be &gt; Total Price.
        /// </summary>
        internal static string Err31 {
            get {
                return ResourceManager.GetString("Err31", resourceCulture);
            }
        }
    }
}
