using System;
using System.Collections.Generic;
using System.Text;

namespace GSM09200COMMON
{
    public class ContextConstant
    {
        public const string GSM09200_PROPERTY_ID_CONTEXT = "GSM09200_PROPERTY_ID_CONTEXT";
        public const string GSM09200_PROPERTY_ID_STREAMING_CONTEXT = "GSM09200_PROPERTY_ID_STREAMING_CONTEXT";

        public const string GSM09210_PROPERTY_ID_CONTEXT = "GSM09210_PROPERTY_ID_CONTEXT";
        public const string GSM09210_EXPENDITURE_ID_CONTEXT = "GSM09210_EXPENDITURE_ID_CONTEXT";
        public const string GSM09210_FROM_EXPENDITURE_CATEGORY_ID_CONTEXT = "GSM09210_FROM_EXPENDITURE_CATEGORY_ID_CONTEXT";
        public const string GSM09210_FROM_EXPENDITURE_CATEGORY_ID_STREAMING_CONTEXT = "GSM09210_FROM_EXPENDITURE_CATEGORY_ID_STREAMING_CONTEXT";
        public const string GSM09210_EXPENDITURE_CATEGORY_ID_CONTEXT = "GSM09210_EXPENDITURE_CATEGORY_ID_CONTEXT";
        public const string GSM09210_TO_EXPENDITURE_CATEGORY_ID_CONTEXT = "GSM09210_TO_EXPENDITURE_CATEGORY_ID_CONTEXT";
        public const string GSM09210_PROPERTY_ID_STREAMING_CONTEXT = "GSM09210_PROPERTY_ID_STREAMING_CONTEXT";

    }
}
