//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APT00900FrontResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class APT00900FrontResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal APT00900FrontResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("APT00900FrontResources.APT00900FrontResources_msgrsc", typeof(APT00900FrontResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocation ID.
        /// </summary>
        internal static string _AllocID {
            get {
                return ResourceManager.GetString("_AllocID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Curr. Base Rate.
        /// </summary>
        internal static string _BCBaseRate {
            get {
                return ResourceManager.GetString("_BCBaseRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Curr. Rate.
        /// </summary>
        internal static string _BCRate {
            get {
                return ResourceManager.GetString("_BCRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string _BTNCancel {
            get {
                return ResourceManager.GetString("_BTNCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose File.
        /// </summary>
        internal static string _BTNChooseFile {
            get {
                return ResourceManager.GetString("_BTNChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        internal static string _BTNProcess {
            get {
                return ResourceManager.GetString("_BTNProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save To Excel.
        /// </summary>
        internal static string _BTNSaveToExcel {
            get {
                return ResourceManager.GetString("_BTNSaveToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        internal static string _BTNTemplate {
            get {
                return ResourceManager.GetString("_BTNTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string _Curr {
            get {
                return ResourceManager.GetString("_Curr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departement.
        /// </summary>
        internal static string _Dept {
            get {
                return ResourceManager.GetString("_Dept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail Notes.
        /// </summary>
        internal static string _DetDesc {
            get {
                return ResourceManager.GetString("_DetDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Ref. Date.
        /// </summary>
        internal static string _DocDate {
            get {
                return ResourceManager.GetString("_DocDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Ref. No.
        /// </summary>
        internal static string _DocNo {
            get {
                return ResourceManager.GetString("_DocNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        internal static string _FileName {
            get {
                return ResourceManager.GetString("_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header Notes.
        /// </summary>
        internal static string _HeadDesc {
            get {
                return ResourceManager.GetString("_HeadDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        internal static string _Invalid {
            get {
                return ResourceManager.GetString("_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Curr. Base Rate.
        /// </summary>
        internal static string _LcBaseRate {
            get {
                return ResourceManager.GetString("_LcBaseRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Curr. Rate.
        /// </summary>
        internal static string _LCRate {
            get {
                return ResourceManager.GetString("_LCRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        internal static string _No {
            get {
                return ResourceManager.GetString("_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTES.
        /// </summary>
        internal static string _Note {
            get {
                return ResourceManager.GetString("_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to process this Invoice?.
        /// </summary>
        internal static string _NotifBeforeProcess {
            get {
                return ResourceManager.GetString("_NotifBeforeProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Invoice Successfully.
        /// </summary>
        internal static string _NotifSuccesUpload {
            get {
                return ResourceManager.GetString("_NotifSuccesUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure download this template?.
        /// </summary>
        internal static string _NotifTemplate {
            get {
                return ResourceManager.GetString("_NotifTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Department.
        /// </summary>
        internal static string _ProdDept {
            get {
                return ResourceManager.GetString("_ProdDept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product ID / Expenditure ID.
        /// </summary>
        internal static string _ProdID {
            get {
                return ResourceManager.GetString("_ProdID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Type.
        /// </summary>
        internal static string _ProdType {
            get {
                return ResourceManager.GetString("_ProdType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string _Property {
            get {
                return ResourceManager.GetString("_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string _QTY {
            get {
                return ResourceManager.GetString("_QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Date.
        /// </summary>
        internal static string _RefDate {
            get {
                return ResourceManager.GetString("_RefDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference No..
        /// </summary>
        internal static string _RefNo {
            get {
                return ResourceManager.GetString("_RefNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier ID.
        /// </summary>
        internal static string _SuppID {
            get {
                return ResourceManager.GetString("_SuppID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Base Rate.
        /// </summary>
        internal static string _TaxBaseRate {
            get {
                return ResourceManager.GetString("_TaxBaseRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Code.
        /// </summary>
        internal static string _TaxCode {
            get {
                return ResourceManager.GetString("_TaxCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Rate.
        /// </summary>
        internal static string _TaxRate {
            get {
                return ResourceManager.GetString("_TaxRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term Code.
        /// </summary>
        internal static string _TermCode {
            get {
                return ResourceManager.GetString("_TermCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Row(s).
        /// </summary>
        internal static string _TotalRow {
            get {
                return ResourceManager.GetString("_TotalRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        internal static string _UnitPrice {
            get {
                return ResourceManager.GetString("_UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VALID.
        /// </summary>
        internal static string _Valid {
            get {
                return ResourceManager.GetString("_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        internal static string _ValidLabel {
            get {
                return ResourceManager.GetString("_ValidLabel", resourceCulture);
            }
        }
    }
}
