//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GLB00600FrontResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GLB00600FrontResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GLB00600FrontResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GLB00600FrontResources.GLB00600FrontResources_msgrsc", typeof(GLB00600FrontResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string _CancelBtn {
            get {
                return ResourceManager.GetString("_CancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Period.
        /// </summary>
        internal static string _CurrentPeriod {
            get {
                return ResourceManager.GetString("_CurrentPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This process will generate a Closing Entries journal by moving the current Earning Amount Produced by the Income Statement into a predifined account in the Balance Sheet.
        /// </summary>
        internal static string _DescClosingEntriesDept {
            get {
                return ResourceManager.GetString("_DescClosingEntriesDept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing Entries Department.
        /// </summary>
        internal static string _LabelClosingEntriesDept {
            get {
                return ResourceManager.GetString("_LabelClosingEntriesDept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to proceed Closing Entries?.
        /// </summary>
        internal static string _NotifAlertBeforeClosingEntries {
            get {
                return ResourceManager.GetString("_NotifAlertBeforeClosingEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing Entries processed successfully!.
        /// </summary>
        internal static string _NotifClosingIsSuccess {
            get {
                return ResourceManager.GetString("_NotifClosingIsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot process Closing Entries Journal with Manual Numbering! Transaction numbering setting for Closing Entries Journal should be auto increment, not manual numbering!.
        /// </summary>
        internal static string _NotifErrorClosingManualNumbering {
            get {
                return ResourceManager.GetString("_NotifErrorClosingManualNumbering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program is only for Year End Process!.
        /// </summary>
        internal static string _NotifErrorOnlyForYearEndProcess {
            get {
                return ResourceManager.GetString("_NotifErrorOnlyForYearEndProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please setup Retained Account No..
        /// </summary>
        internal static string _NotifErrorSetupRetained {
            get {
                return ResourceManager.GetString("_NotifErrorSetupRetained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please setup Suspense Account No..
        /// </summary>
        internal static string _NotifErrorSetupSuspence {
            get {
                return ResourceManager.GetString("_NotifErrorSetupSuspence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soft Close GL Period should be done prior to Close GL Period.
        /// </summary>
        internal static string _NotifErrorSoftClose {
            get {
                return ResourceManager.GetString("_NotifErrorSoftClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspense Account journal found!.
        /// </summary>
        internal static string _NotifErrorSuspenseAccountJrnl {
            get {
                return ResourceManager.GetString("_NotifErrorSuspenseAccountJrnl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} does not have access to department {1}.
        /// </summary>
        internal static string _NotifErrorUserNotHaveAccessDept {
            get {
                return ResourceManager.GetString("_NotifErrorUserNotHaveAccessDept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must maintain GL System Parameter for property {0}.
        /// </summary>
        internal static string _NotifMustMaintainParamProperty {
            get {
                return ResourceManager.GetString("_NotifMustMaintainParamProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        internal static string _ProcessBtn {
            get {
                return ResourceManager.GetString("_ProcessBtn", resourceCulture);
            }
        }
    }
}
