//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GLR00200FrontResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GLR00200FrontResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GLR00200FrontResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GLR00200FrontResources.GLR00200FrontResources_msgrsc", typeof(GLR00200FrontResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string _Account {
            get {
                return ResourceManager.GetString("_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Currency.
        /// </summary>
        internal static string _BaseCurr {
            get {
                return ResourceManager.GetString("_BaseCurr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing.
        /// </summary>
        internal static string _Closing {
            get {
                return ResourceManager.GetString("_Closing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Type.
        /// </summary>
        internal static string _CurrType {
            get {
                return ResourceManager.GetString("_CurrType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string _Date {
            get {
                return ResourceManager.GetString("_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string _From {
            get {
                return ResourceManager.GetString("_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Audit Journal.
        /// </summary>
        internal static string _IncludeAuditJrnl {
            get {
                return ResourceManager.GetString("_IncludeAuditJrnl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Currency.
        /// </summary>
        internal static string _LocalCurr {
            get {
                return ResourceManager.GetString("_LocalCurr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        internal static string _Period {
            get {
                return ResourceManager.GetString("_Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string _PrintBtn {
            get {
                return ResourceManager.GetString("_PrintBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print by Center.
        /// </summary>
        internal static string _PrintByCenter {
            get {
                return ResourceManager.GetString("_PrintByCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Method.
        /// </summary>
        internal static string _PrintMethod {
            get {
                return ResourceManager.GetString("_PrintMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Options.
        /// </summary>
        internal static string _ReportOption {
            get {
                return ResourceManager.GetString("_ReportOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string _To {
            get {
                return ResourceManager.GetString("_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string _Year {
            get {
                return ResourceManager.GetString("_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select From Account No..
        /// </summary>
        internal static string Err2001 {
            get {
                return ResourceManager.GetString("Err2001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select To Account No..
        /// </summary>
        internal static string Err2002 {
            get {
                return ResourceManager.GetString("Err2002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select from Center Code!.
        /// </summary>
        internal static string Err2003 {
            get {
                return ResourceManager.GetString("Err2003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select to Center Code!.
        /// </summary>
        internal static string Err2004 {
            get {
                return ResourceManager.GetString("Err2004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select from Period Code!.
        /// </summary>
        internal static string Err2005 {
            get {
                return ResourceManager.GetString("Err2005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select to Period Code!.
        /// </summary>
        internal static string Err2006 {
            get {
                return ResourceManager.GetString("Err2006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date is required!.
        /// </summary>
        internal static string Err2007 {
            get {
                return ResourceManager.GetString("Err2007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date is required!.
        /// </summary>
        internal static string Err2008 {
            get {
                return ResourceManager.GetString("Err2008", resourceCulture);
            }
        }
    }
}
