//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APM00300FrontResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class APM00300FrontResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal APM00300FrontResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("APM00300FrontResources.APM00300FrontResources_msgrsc", typeof(APM00300FrontResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Property!.
        /// </summary>
        internal static string _301 {
            get {
                return ResourceManager.GetString("301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input keyword to search!.
        /// </summary>
        internal static string _302 {
            get {
                return ResourceManager.GetString("302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum search keyword is 3 characters!.
        /// </summary>
        internal static string _303 {
            get {
                return ResourceManager.GetString("303", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier ID is required!.
        /// </summary>
        internal static string _304 {
            get {
                return ResourceManager.GetString("304", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Name is required!.
        /// </summary>
        internal static string _305 {
            get {
                return ResourceManager.GetString("305", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Group is required!.
        /// </summary>
        internal static string _306 {
            get {
                return ResourceManager.GetString("306", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category is required!.
        /// </summary>
        internal static string _307 {
            get {
                return ResourceManager.GetString("307", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term is required!.
        /// </summary>
        internal static string _308 {
            get {
                return ResourceManager.GetString("308", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency is required!.
        /// </summary>
        internal static string _309 {
            get {
                return ResourceManager.GetString("309", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line of Business is required!.
        /// </summary>
        internal static string _310 {
            get {
                return ResourceManager.GetString("310", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address is required!.
        /// </summary>
        internal static string _311 {
            get {
                return ResourceManager.GetString("311", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City is required!.
        /// </summary>
        internal static string _312 {
            get {
                return ResourceManager.GetString("312", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone 1 is required!.
        /// </summary>
        internal static string _313 {
            get {
                return ResourceManager.GetString("313", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email 1 is invalid!.
        /// </summary>
        internal static string _314 {
            get {
                return ResourceManager.GetString("314", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email 2 is invalid!.
        /// </summary>
        internal static string _315 {
            get {
                return ResourceManager.GetString("315", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person 1 Email is invalid!.
        /// </summary>
        internal static string _316 {
            get {
                return ResourceManager.GetString("316", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person 2 Email is invalid!.
        /// </summary>
        internal static string _317 {
            get {
                return ResourceManager.GetString("317", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Type is required!.
        /// </summary>
        internal static string _318 {
            get {
                return ResourceManager.GetString("318", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Name is required for Registrant Tax Type!.
        /// </summary>
        internal static string _319 {
            get {
                return ResourceManager.GetString("319", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Registration ID is required for Registrant Tax Type!.
        /// </summary>
        internal static string _320 {
            get {
                return ResourceManager.GetString("320", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Registration Date is required for Registrant Tax Type!.
        /// </summary>
        internal static string _321 {
            get {
                return ResourceManager.GetString("321", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Code is required!.
        /// </summary>
        internal static string _322 {
            get {
                return ResourceManager.GetString("322", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No. is required!.
        /// </summary>
        internal static string _323 {
            get {
                return ResourceManager.GetString("323", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name is required!.
        /// </summary>
        internal static string _324 {
            get {
                return ResourceManager.GetString("324", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite is required!.
        /// </summary>
        internal static string _325 {
            get {
                return ResourceManager.GetString("325", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch is required!.
        /// </summary>
        internal static string _326 {
            get {
                return ResourceManager.GetString("326", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        internal static string _AccountName {
            get {
                return ResourceManager.GetString("_AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No.
        /// </summary>
        internal static string _AccountNo {
            get {
                return ResourceManager.GetString("_AccountNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string _Active {
            get {
                return ResourceManager.GetString("_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string _Addr {
            get {
                return ResourceManager.GetString("_Addr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string _Balance {
            get {
                return ResourceManager.GetString("_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        internal static string _Bank {
            get {
                return ResourceManager.GetString("_Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        internal static string _Branch {
            get {
                return ResourceManager.GetString("_Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string _CancelBtn {
            get {
                return ResourceManager.GetString("_CancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string _Category {
            get {
                return ResourceManager.GetString("_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string _City {
            get {
                return ResourceManager.GetString("_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string _Code {
            get {
                return ResourceManager.GetString("_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy From.
        /// </summary>
        internal static string _Copy_From {
            get {
                return ResourceManager.GetString("_Copy From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string _Country {
            get {
                return ResourceManager.GetString("_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person 1.
        /// </summary>
        internal static string _CP1 {
            get {
                return ResourceManager.GetString("_CP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person 2.
        /// </summary>
        internal static string _CP2 {
            get {
                return ResourceManager.GetString("_CP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        internal static string _CreateBy {
            get {
                return ResourceManager.GetString("_CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        internal static string _CreateDate {
            get {
                return ResourceManager.GetString("_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string _Currency {
            get {
                return ResourceManager.GetString("_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Options.
        /// </summary>
        internal static string _DeliverOptions {
            get {
                return ResourceManager.GetString("_DeliverOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DP Amount.
        /// </summary>
        internal static string _DPAmount {
            get {
                return ResourceManager.GetString("_DPAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string _Email {
            get {
                return ResourceManager.GetString("_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude Delivery Fee, Insurance, etc..
        /// </summary>
        internal static string _ExcludeDelivery {
            get {
                return ResourceManager.GetString("_ExcludeDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite Name.
        /// </summary>
        internal static string _FavName {
            get {
                return ResourceManager.GetString("_FavName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string _Fax {
            get {
                return ResourceManager.GetString("_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Delivery Fee, Insurance, etc..
        /// </summary>
        internal static string _IncludeDelivery {
            get {
                return ResourceManager.GetString("_IncludeDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Group.
        /// </summary>
        internal static string _JrnlGrp {
            get {
                return ResourceManager.GetString("_JrnlGrp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Payment.
        /// </summary>
        internal static string _LAstPayment {
            get {
                return ResourceManager.GetString("_LAstPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Purchase.
        /// </summary>
        internal static string _LastPurch {
            get {
                return ResourceManager.GetString("_LastPurch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Of Business.
        /// </summary>
        internal static string _LineOfBusiness {
            get {
                return ResourceManager.GetString("_LineOfBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line of Business Code*.
        /// </summary>
        internal static string _LOBCode {
            get {
                return ResourceManager.GetString("_LOBCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Info.
        /// </summary>
        internal static string _MainInfo {
            get {
                return ResourceManager.GetString("_MainInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string _Name {
            get {
                return ResourceManager.GetString("_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Payment.
        /// </summary>
        internal static string _NoPayment {
            get {
                return ResourceManager.GetString("_NoPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Purchase.
        /// </summary>
        internal static string _NoPurchase {
            get {
                return ResourceManager.GetString("_NoPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Purchase &amp; No Payment.
        /// </summary>
        internal static string _NoPurchasePayment {
            get {
                return ResourceManager.GetString("_NoPurchasePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string _Normal {
            get {
                return ResourceManager.GetString("_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string _OkBtn {
            get {
                return ResourceManager.GetString("_OkBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Time.
        /// </summary>
        internal static string _OneTime {
            get {
                return ResourceManager.GetString("_OneTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string _Phone {
            get {
                return ResourceManager.GetString("_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO Amount.
        /// </summary>
        internal static string _PoAmount {
            get {
                return ResourceManager.GetString("_PoAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string _Position {
            get {
                return ResourceManager.GetString("_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        internal static string _ProcessBtn {
            get {
                return ResourceManager.GetString("_ProcessBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string _Property {
            get {
                return ResourceManager.GetString("_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string _Refresh {
            get {
                return ResourceManager.GetString("_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string _Save {
            get {
                return ResourceManager.GetString("_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string _Search {
            get {
                return ResourceManager.GetString("_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence No..
        /// </summary>
        internal static string _SeqNo {
            get {
                return ResourceManager.GetString("_SeqNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All.
        /// </summary>
        internal static string _ShowAll {
            get {
                return ResourceManager.GetString("_ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string _State {
            get {
                return ResourceManager.GetString("_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string _Status {
            get {
                return ResourceManager.GetString("_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        internal static string _Supp {
            get {
                return ResourceManager.GetString("_Supp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Detail.
        /// </summary>
        internal static string _SuppDetail {
            get {
                return ResourceManager.GetString("_SuppDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier ID.
        /// </summary>
        internal static string _SuppId {
            get {
                return ResourceManager.GetString("_SuppId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier ID / Name*.
        /// </summary>
        internal static string _SuppIdName {
            get {
                return ResourceManager.GetString("_SuppIdName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Name.
        /// </summary>
        internal static string _SuppName {
            get {
                return ResourceManager.GetString("_SuppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Status.
        /// </summary>
        internal static string _SuppStatus {
            get {
                return ResourceManager.GetString("_SuppStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address &amp; Contact.
        /// </summary>
        internal static string _TabAddrContact {
            get {
                return ResourceManager.GetString("_TabAddrContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax &amp; Balance Info.
        /// </summary>
        internal static string _TabtaxBalance {
            get {
                return ResourceManager.GetString("_TabtaxBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Info.
        /// </summary>
        internal static string _TabTaxInfo {
            get {
                return ResourceManager.GetString("_TabTaxInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Name.
        /// </summary>
        internal static string _TaxName {
            get {
                return ResourceManager.GetString("_TaxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Registarion Date.
        /// </summary>
        internal static string _TaxRegDate {
            get {
                return ResourceManager.GetString("_TaxRegDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Registarion ID.
        /// </summary>
        internal static string _TaxRegID {
            get {
                return ResourceManager.GetString("_TaxRegID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Type.
        /// </summary>
        internal static string _TaxType {
            get {
                return ResourceManager.GetString("_TaxType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term.
        /// </summary>
        internal static string _Term {
            get {
                return ResourceManager.GetString("_Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated By.
        /// </summary>
        internal static string _UpdateBy {
            get {
                return ResourceManager.GetString("_UpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Date.
        /// </summary>
        internal static string _UpdateDate {
            get {
                return ResourceManager.GetString("_UpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        internal static string _ZipCode {
            get {
                return ResourceManager.GetString("_ZipCode", resourceCulture);
            }
        }
    }
}
