//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSM03000FrontResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GSM03000FrontResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GSM03000FrontResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GSM03000FrontResources.GSM03000FrontResources_msgrsc", typeof(GSM03000FrontResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges Id is required.
        /// </summary>
        internal static string _3009 {
            get {
                return ResourceManager.GetString("3009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges Name is required.
        /// </summary>
        internal static string _3010 {
            get {
                return ResourceManager.GetString("3010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GL ACCOUNT is required.
        /// </summary>
        internal static string _3011 {
            get {
                return ResourceManager.GetString("3011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges Id Maximum 20 Character.
        /// </summary>
        internal static string _3012 {
            get {
                return ResourceManager.GetString("3012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges Name Maximum 100 Character.
        /// </summary>
        internal static string _3013 {
            get {
                return ResourceManager.GetString("3013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string _Active {
            get {
                return ResourceManager.GetString("_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Charges.
        /// </summary>
        internal static string _AdditionalTabTittle {
            get {
                return ResourceManager.GetString("_AdditionalTabTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges Description.
        /// </summary>
        internal static string _ChargesDesc {
            get {
                return ResourceManager.GetString("_ChargesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges Id.
        /// </summary>
        internal static string _ChargesId {
            get {
                return ResourceManager.GetString("_ChargesId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Charges Id*.
        /// </summary>
        internal static string _ChargesIdAdditional {
            get {
                return ResourceManager.GetString("_ChargesIdAdditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deducation Charges Id*.
        /// </summary>
        internal static string _ChargesIdDeducation {
            get {
                return ResourceManager.GetString("_ChargesIdDeducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges Name.
        /// </summary>
        internal static string _ChargesName {
            get {
                return ResourceManager.GetString("_ChargesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        internal static string _CreateBy {
            get {
                return ResourceManager.GetString("_CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        internal static string _CreateDate {
            get {
                return ResourceManager.GetString("_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deducation Charges.
        /// </summary>
        internal static string _DeducationTabTittle {
            get {
                return ResourceManager.GetString("_DeducationTabTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GL Account No*.
        /// </summary>
        internal static string _GLAccountNo {
            get {
                return ResourceManager.GetString("_GLAccountNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GL ACCOUNT SETUP.
        /// </summary>
        internal static string _GLAccountSetup {
            get {
                return ResourceManager.GetString("_GLAccountSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Valid when GL Journal Link Enable).
        /// </summary>
        internal static string _GLAccountSetupDesc {
            get {
                return ResourceManager.GetString("_GLAccountSetupDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string _PrintBtn {
            get {
                return ResourceManager.GetString("_PrintBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Inactive Charge.
        /// </summary>
        internal static string _PrintInactiveCharges {
            get {
                return ResourceManager.GetString("_PrintInactiveCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string _Property {
            get {
                return ResourceManager.GetString("_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short By.
        /// </summary>
        internal static string _ShortBy {
            get {
                return ResourceManager.GetString("_ShortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated By.
        /// </summary>
        internal static string _UpdateBy {
            get {
                return ResourceManager.GetString("_UpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Date.
        /// </summary>
        internal static string _UpdateDate {
            get {
                return ResourceManager.GetString("_UpdateDate", resourceCulture);
            }
        }
    }
}
