using System;
using System.Collections.Generic;
using System.Text;

namespace LMM03500COMMON
{
    public class ContextConstant
    {
        public const string LMM03500_PROPERTY_ID_STREAMING_CONTEXT = "LMM03500_PROPERTY_ID_STREAMING_CONTEXT";
        public const string LMM03500_PROPERTY_ID_CONTEXT = "LMM03500_PROPERTY_ID_CONTEXT";
        public const string LMM03500_TENANT_ID_CONTEXT = "LMM03500_TENANT_ID_CONTEXT";

        public const string LMM03501_PROPERTY_ID_STREAMING_CONTEXT = "LMM03501_PROPERTY_ID_STREAMING_CONTEXT";

        public const string LMM03502_PROPERTY_ID_STREAMING_CONTEXT = "LMM03502_PROPERTY_ID_STREAMING_CONTEXT";
        public const string LMM03502_PROPERTY_ID_CONTEXT = "LMM03502_PROPERTY_ID_CONTEXT";
        public const string LMM03502_TENANT_ID_CONTEXT = "LMM03502_TENANT_ID_CONTEXT";

        public const string LMM03503_PROPERTY_ID_CONTEXT = "LMM03503_PROPERTY_ID_CONTEXT";
        public const string LMM03503_TENANT_ID_CONTEXT = "LMM03503_TENANT_ID_CONTEXT";

        public const string LMM03504_PROPERTY_ID_CONTEXT = "LMM03504_PROPERTY_ID_CONTEXT";
        public const string LMM03504_TENANT_ID_CONTEXT = "LMM03504_TENANT_ID_CONTEXT";

        public const string LMM03505_PROPERTY_ID_STREAMING_CONTEXT = "LMM03505_PROPERTY_ID_STREAMING_CONTEXT";
        public const string LMM03505_TENANT_ID_STREAMING_CONTEXT = "LMM03505_TENANT_ID_STREAMING_CONTEXT";
        public const string LMM03505_PROPERTY_ID_CONTEXT = "LMM03505_PROPERTY_ID_CONTEXT";
        public const string LMM03505_TENANT_ID_CONTEXT = "LMM03505_TENANT_ID_CONTEXT";

        public const string LMM03507_PROPERTY_ID_STREAMING_CONTEXT = "LMM03507_PROPERTY_ID_STREAMING_CONTEXT";
        public const string LMM03507_TENANT_ID_STREAMING_CONTEXT = "LMM03507_TENANT_ID_STREAMING_CONTEXT";
        public const string LMM03507_PROPERTY_ID_CONTEXT = "LMM03507_PROPERTY_ID_CONTEXT";
        public const string LMM03507_BIRTH_DATE_CONTEXT = "LMM03507_BIRTH_DATE_CONTEXT";

        public const string LMM03508_PROPERTY_ID_STREAMING_CONTEXT = "LMM03508_PROPERTY_ID_STREAMING_CONTEXT";
        public const string LMM03508_TENANT_ID_STREAMING_CONTEXT = "LMM03508_TENANT_ID_STREAMING_CONTEXT";

        public const string UPLOAD_TENANT_PROPERTY_ID_CONTEXT = "UPLOAD_TENANT_PROPERTY_ID_CONTEXT";
        public const string UPLOAD_TENANT_IS_OVERWRITE_CONTEXT = "UPLOAD_TENANT_IS_OVERWRITE_CONTEXT";
        public const string UPLOAD_TENANT_STREAMING_CONTEXT = "UPLOAD_TENANT_STREAMING_CONTEXT";
        public const string UPLOAD_TENANT_ERROR_GUID_STREAMING_CONTEXT = "UPLOAD_TENANT_ERROR_GUID_STREAMING_CONTEXT";
    }
}
